name: Model Retraining on Push to Main - Github Lab 2

on:
  push:
    branches:
      - main

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v1
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"

    - name: Set up Python
      run: uv python install 3.9

    - name: Sync dependencies
      run: uv sync

    - name: Generate and Store Timestamp
      id: timestamp
      run: |
        timestamp=$(date '+%Y%m%d%H%M%S')
        echo "$timestamp" > timestamp.txt
        echo "timestamp=$timestamp" >> $GITHUB_ENV

    - name: Check File Permissions
      run: ls -l Github_Labs/Lab2/src/train_model.py

    - name: Set File Permissions
      run: chmod +x Github_Labs/Lab2/src/train_model.py

    - name: Retrain Model
      run: |
        uv run python Github_Labs/Lab2/src/train_model.py --timestamp "$timestamp"

    - name: Evaluate Model and Log Metrics
      run: |
        uv run python Github_Labs/Lab2/src/evaluate_model.py --timestamp "$timestamp"
        metrics_filename="${timestamp}_metrics.json"
        mkdir -p Github_Labs/Lab2/metrics
        mv "$metrics_filename" "Github_Labs/Lab2/metrics/$metrics_filename"

    - name: Store and Version the New Model
      run: |
        model_filename="model_${timestamp}_xgb_model.joblib"
        mkdir -p Github_Labs/Lab2/models
        mv "$model_filename" "Github_Labs/Lab2/models/$model_filename"

    - name: Commit and Push Changes
      run: |
        git config --global user.email "35000278+MDhamani@users.noreply.github.com"
        git config --global user.name "MDhamani"
        metrics_filename="Github_Labs/Lab2/metrics/${timestamp}_metrics.json"
        model_filename="Github_Labs/Lab2/models/model_${timestamp}_xgb_model.joblib"
        git add -f "$metrics_filename" "$model_filename"
        # Commit only if there are changes
        if ! git diff --cached --quiet; then
          git commit -m "Add metrics and updated model for $timestamp"
          git push
        else
          echo "No changes to commit."
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}